### ISSUE TITLE
Include the source code directly

### ISSUE THREAD

**Issue by jhdcruz** [SilverousBlack/matrix.h#1]
It is not recommended to upload compressed files, **include the source code itself**. Doing so will help GitHub to do some Code Analysis on what language is used and fast preview of the contents in it without having to download the compressed file.

Downloading the repo manually will automatically compress the whole files.

**Comment by jhdcruz** [comment]
**Tags/Releases** is the one that is used for build files/release files.

**Comment by SilverousBlack** [comment]
Got it! Thanks~!
